---
version: '3.8'

services:
  backend:
    image: diegorlopez/pokedex-backend:1.8.0
    container_name: pokedex-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - ALLOWED_ORIGINS=http://localhost:5500,http://localhost:3000,http://localhost:80
    depends_on:
      - redis
      - postgres
    restart: unless-stopped

  frontend:
    # ← Imagen con Nginx
    image: diegorlopez/pokedex-frontend:nginx
    container_name: pokedex-frontend
    ports:
      # ← Host:5500 → Container:80 (Nginx)
      - "5500:80"
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pokedex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    container_name: pokedex-postgres
    environment:
      POSTGRES_DB: pokedex_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
