[all]
sre-runner ansible_host=192.168.56.10
sre-monitor ansible_host=192.168.56.11
sre-storage ansible_host=192.168.56.12
k3s-master ansible_host=192.168.56.20
k3s-worker ansible_host=192.168.56.21

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/id_ed25519_ansible
ansible_ssh_common_args='-o StrictHostKeyChecking=no'