name: "SRE Platform Pipeline"

on:
  push:
    branches: [ main, 'feature/**' ]
    paths:
      - 'infrastructure/**'
      - '.github/workflows/pipeline.yml'
  workflow_dispatch: # Allows manual execution from GitHub UI

jobs:
  # JOB 1: Validation (Runs on all branches to ensure code quality)
  quality-gates:
    name: "Lint & Security Scan"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: YAML Lint
        run: yamllint .

      - name: Ansible Lint
        run: ansible-lint infrastructure/ansible/site.yml

      - name: Trivy Security Scan
        run: |
          # Scan filesystem for secrets, misconfigurations and vulnerabilities
          trivy fs --severity HIGH,CRITICAL --exit-code 1 .

  # JOB 2: Deployment (Only runs if Quality Gates pass AND branch is main)
  deploy-infrastructure:
    name: "Continuous Deployment"
    needs: quality-gates
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Provision Storage Layer
        run: |
          # Change directory to Ansible root
          cd infrastructure/ansible
          # Execute playbook targeting only the storage node for efficiency
          ansible-playbook -i inventory/hosts.ini site.yml --limit sre-storage

  # JOB 3: Connectivity & Telemetry
  inventory-check:
    name: "Connectivity tests"
    needs: deploy-infrastructure
    runs-on: self-hosted 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: System Telemetry
        run: |
          echo "==> Diagnostic: Host Telemetry"
          hostname
          uptime
          free -h
          
      - name: Ansible Connectivity Test
        run: |
          echo "==> Diagnostic: Checking Ansible Inventory"
          # No 'cd' needed because we use the absolute path generated by Vagrant
          ansible all -i /home/vagrant/ansible/hosts.ini -m ping
    