name: Storage Provisioning
on:
  push:
    branches: [ main, feature/ansible-zfs-storage ]
    paths:
      - 'infrastructure/ansible/**'
  workflow_dispatch:
jobs:
  deploy-zfs:
    runs-on: self-hosted  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run ZFS Playbook
        run: |
          cd infrastructure/ansible
          ansible-playbook -i /home/vagrant/ansible/hosts.ini site.yml