---
- name: "1. Ensure contrib, non-free and firmware repositories"
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian/ bookworm main contrib non-free non-free-firmware"
    state: present

- name: "2. Update cache and perform dist-upgrade"
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: "3. Install ZFS utilities and Kernel Headers"
  ansible.builtin.apt:
    name:
      - zfsutils-linux
      - linux-headers-amd64
    state: present

- name: "4. Check if reboot is required"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: "5. Reboot if Kernel has changed"
  ansible.builtin.reboot:
    msg: "SRE Alert: Rebooting to apply new Kernel"
  when: reboot_required_file.stat.exists

- name: "6. Create ZFS Pool in Mirror mode"
  community.general.zpool:
    name: "{{ pool_name }}"
    vdevs:
      - type: mirror
        disks: "{{ disks }}"
    state: present

- name: "7. Create PostgreSQL optimized Dataset (8k)"
  community.general.zfs:
    name: "{{ pool_name }}/postgres"
    state: present
    extra_zfs_properties:
      recordsize: 8k
      compression: lz4

- name: "8. Create VM dataset"
  community.general.zfs:
    name: "{{ pool_name }}/vm"
    state: present
    extra_zfs_properties:
      recordsize: 128k
      compression: lz4
      atime: off

- name: "9. Create Loki dataset"
  community.general.zfs:
    name: "{{ pool_name }}/loki"
    state: present
    extra_zfs_properties:
      recordsize: 128k
      compression: zstd # Mejor ratio para texto
      atime: off
